spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shiro?characterEncoding=utf-8
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
    
mybatis:
  type-aliases-package: com.ysd.entity
  mapper-locations: classpath:mapper/*.xml
   
